### ISSUE TITLE
Example of using Jacobian with args and kwds?

### ISSUE THREAD

**Issue by mdornfe1** [pbrod/numdifftools#14]
Can you provide an example of using Jacobian with args?

I have a function 

def f(x, args):
    pass

I tried 

x0 
jac = Jacobian(f)
jac(x0, args)

This produces the error

TypeError                                 Traceback (most recent call last)
<ipython-input-66-86e601a44004> in <module>()
----> 1 jac(q0,params)

/usr/local/lib/python2.7/dist-packages/numdifftools/core.pyc in __call__(self, x, *args, **kwds)
   1112 
   1113     def __call__(self, x, *args, **kwds):
-> 1114         return super(Gradient, self).__call__(np.atleast_1d(x), *args, **kwds)
   1115 
   1116 

/usr/local/lib/python2.7/dist-packages/numdifftools/core.pyc in __call__(self, x, *args, **kwds)
    747     def __call__(self, x, *args, **kwds):
    748         xi = np.asarray(x)
--> 749         results = self._derivative(xi, args, kwds)
    750         derivative, info = self._extrapolate(*results)
    751         if self.full_output:

/usr/local/lib/python2.7/dist-packages/numdifftools/core.pyc in _derivative(self, xi, args, kwds)
    945         steps = self._get_steps(xi)
    946         fxi = self._eval_first(f, xi, *args, **kwds)
--> 947         results = [diff(f, fxi, xi, h, *args, **kwds) for h in steps]
    948         step_ratio = self._compute_step_ratio(steps)
    949 

/usr/local/lib/python2.7/dist-packages/numdifftools/core.pyc in _central(f, fx, x, h, *args, **kwds)
   1067         increments = np.identity(n) * h
   1068         partials = [(f(x + hi, *args, **kwds) - f(x - hi, *args, **kwds)) / 2.0
-> 1069                     for hi in increments]
   1070         return np.array(partials).T
   1071 

TypeError: unsupported operand type(s) for -: 'list' and 'list'

**Comment by pbrod** [comment]
>>> def f(x, y): 
return np.exp(-x**2-args[0]**2)

In [96]: df = nd.Derivative(f)

In [97]: x = np.linspace(-2,2)

In [98]: X,Y = np.meshgrid(x,x)

In [99]: z = df(x,y)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-99-026854c54f18> in <module>()
----> 1 z = df(x,y)

NameError: name 'y' is not defined

In [100]: z = df(X,Y)

In [101]: plt.contourf(x,x,z)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-101-51c00ce29d86> in <module>()
----> 1 plt.contourf(x,x,z)

NameError: name 'plt' is not defined

In [102]: import pylab as plt

In [103]: plt.contourf(x,x,z)
Out[103]: <matplotlib.contour.QuadContourSet instance at 0x00000000022180C8>
￼

In [104]:

**Comment by pbrod** [comment]
Here is one example on how to pass on additional arguments (*args) and keyword arguments (**kwds) to a function using Jacobian in numdifftools:

    >>> import numpy as np
    >>> import numdifftools as nd
    >>> import pylab as plt
    >>> def f(x, y=1, z=1): return np.sum(-x**2) * y * z  
    >>> jac = nd.Jacobian(f)

    >>> x = np.arange(3)
    >>> jac(1,2)
    array([-4.])

    >>> jac(1,2,3)
    array([-12.])

    >>> x = np.arange(3)
    >>> jac(x,2,3)
    array([  0., -12., -24.])
    >>> jac(x,2,z=3)
    array([  0., -12., -24.])

    >>> jac(x,2,z=4)
    array([  0., -16., -32.])

**Comment by pbrod** [comment]
closing this issue
