### ISSUE TITLE
remove sphinx/numpydoc from requirements.txt

### ISSUE THREAD

**Issue by pkienzle** [pbrod/numdifftools#15]
I was surprised to have my sphinx version updated when I installed numdifftools.  Do you really need the following packages from requirements.txt to run numdifftools?

    numpydoc>=0.5
    sphinx_rtd_theme>=0.1.7

**Comment by pbrod** [comment]
It is only needed for building the documentation.

**Comment by pbrod** [comment]
Moved the requirements:

numpydoc>=0.5
sphinx_rtd_theme>=0.1.7

to requirements.readthedocs.txt
