### ISSUE TITLE
Support for multiple dimensions?

### ISSUE THREAD

**Issue by solarjoe** [pbrod/numdifftools#16]
Hello,
is there a way to calculate directional derivatives of a function
using numdifftools, as with directionaldiff or gradest from Matlab's derivest?

Kind regards,
Joe

**Comment by pbrod** [comment]
The directional derivative will be the dot product of the gradient with the (unit normalized) vector. This is of course possible to do with numdifftools and you could do it like this:

    >>> import numpy as np
    >>> import numdifftools as nd
    >>> v = np.r_[1, -1]
    >>> v = v/np.linalg.norm(v)
    >>> x0 = [2, 3]
    >>> def rosen(x): return (1-x[0])**2 + 105.*(x[1]-x[0]**2)**2
    >>> directional_diff = np.dot(nd.Gradient(rosen)(x0), v)
    >>> directional_diff
    743.87633380824832

**Comment by pbrod** [comment]
The above example is now included in the documentation. 
Also a function directionaldiff is added in commit d22e9fa2936459af48d8a126722dd0ce2a901154

**Comment by pbrod** [comment]
Thanks @solarjoe

**Comment by solarjoe** [comment]
Thanks a lot @pbrod for the quick change and this module.
Since I changed from Matlab to Python the Derivest toolbox was 
one of the few things I missed a lot in Python for the last years.

My workaround function for directionaldiff looked nearly
the same as yours, I guess we both translated from Matlab :)

The chapter "Multivariate calculus examples" you added to 
docs/src/numerical/derivest.rst
does show how to calculate the directional diff with Gradient and np.dot
but does not mention the new function yet.
