### ISSUE TITLE
multiple observations mishandled in Jacobian

### ISSUE THREAD

**Issue by mikofski** [pbrod/numdifftools#19]
Thank you so much for this tool. Also I am a long time fan of [John D'Errico from MATLAB FEX](http://www.mathworks.com/matlabcentral/profile/authors/869215-john-d-errico).

According to the [documentation on Jacobian](http://numdifftools.readthedocs.org/en/latest/api/generated/numdifftools.core.Jacobian.html) it says:

>If f returns a 1d array, it returns a Jacobian. If a 2d array is returned by f (e.g., with a value for each observation), it returns a 3d array with the Jacobian of each observation with shape xk x nobs x xk. I.e., the Jacobian of the first observation would be [:, 0, :]

But that is not what I observe. Consider the following function. ALGOPY returns the following Jacobian:

```python
import numpy as np
from algopy import zeros as azeros
import numdifftools.nd_algopy as nda

def f(x):
    f0 = x[0] ** 2 + x[1] ** 2
    f1 = x[0] ** 3 + x[1] ** 3
    s0 = f0.size
    s1 = f1.size
    out = azeros((2, (s0 + s1) / 2),dtype=x)
    out[0,:] = f0
    out[1,:] = f1
    return out

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8)],dtype=float)
# array([[ 1.,  2.,  3.,  4.],
#        [ 5.,  6.,  7.,  8.]])
y = f(x)
#array([[  26.,   40.,   58.,   80.],
#       [ 126.,  224.,  370.,  576.]])
jaca = nda.Jacobian(f)
j = jaca(x)
#array([[[   2.,    0.,    0.,    0.,   10.,    0.,    0.,    0.],
#        [   0.,    4.,    0.,    0.,    0.,   12.,    0.,    0.],
#        [   0.,    0.,    6.,    0.,    0.,    0.,   14.,    0.],
#        [   0.,    0.,    0.,    8.,    0.,    0.,    0.,   16.]],
#
#       [[   3.,    0.,    0.,    0.,   75.,    0.,    0.,    0.],
#        [   0.,   12.,    0.,    0.,    0.,  108.,    0.,    0.],
#        [   0.,    0.,   27.,    0.,    0.,    0.,  147.,    0.],
#        [   0.,    0.,    0.,   48.,    0.,    0.,    0.,  192.]]])
```

This is what I expected to happen. Each observation and corresponding function evaluation is treated like a separate independent variable. And since the function returns a 2d array, the Jacobian is 3d.

However when I try the same thing with `numdifftools` I get inconsistent results.:
* if the number of observations is less than or equal to the degrees of freedom, then the observations are added together, depending on how I shape the arguments and the return value
* if the number of observations is greater than the degrees of freedom, then I get a stacktrace.

```python
import numpy as np
import numdifftools as nd

def g(x):
    f0 = x[0]**2 + x[1]**2
    f1 = x[0]**3 + x[1]**3
    return np.array([f0, f1])

x = np.array([(1, 2, 3, 4),(5, 6, 7, 8)],dtype=float)
# array([[ 1.,  2.,  3.,  4.],
#        [ 5.,  6.,  7.,  8.]])
y = g(x)
#array([[  26.,   40.,   58.,   80.],
#       [ 126.,  224.,  370.,  576.]])
jac = nd.Jacobian(g)
jac([1, 2])
#array([[  2.,   4.],
#       [  3.,  12.]])
jac([(1, 3), (2, 4)])
#array([[[  6.        ,   0.        ],
#        [ 13.6535884 ,   0.        ]],
#
#       [[  0.        ,  16.25349666],
#        [  0.        ,  75.        ]]])
j = jac(x)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-0da34a79b9f7> in <module>()
----> 1 j = jac(x)

c:\python27\lib\site-packages\numdifftools\core.pyc in __call__(self, x, *args, **kwds)
   1032
   1033     def __call__(self, x, *args, **kwds):
-> 1034         return super(Gradient, self).__call__(np.atleast_1d(x), *args, **kwds)
   1035
   1036

c:\python27\lib\site-packages\numdifftools\core.pyc in __call__(self, x, *args, **kwds)
    647     def __call__(self, x, *args, **kwds):
    648         xi = np.asarray(x)
--> 649         results = self._derivative(xi, args, kwds)
    650         derivative, info = self._extrapolate(*results)
    651         if self.full_output:

c:\python27\lib\site-packages\numdifftools\core.pyc in _derivative_nonzero_order(self, xi, args, kwds)
    866         steps = self._get_steps(xi)
    867         fxi = self._eval_first(f, xi, *args, **kwds)
--> 868         results = [diff(f, fxi, xi, h, *args, **kwds) for h in steps]
    869         step_ratio = self._compute_step_ratio(steps)
    870

c:\python27\lib\site-packages\numdifftools\core.pyc in _central(f, fx, x, h, *args, **kwds)
    986     def _central(f, fx, x, h, *args, **kwds):
    987         n = len(x)
--> 988         increments = np.identity(n) * h
    989         partials = [(f(x + hi, *args, **kwds) - f(x - hi, *args, **kwds)) / 2.0
    990                     for hi in increments]

ValueError: operands could not be broadcast together with shapes (2,2) (2,4)
```

I will look into the source when I have more time, and in the meantime, the ALGOPY methods much more performant.

Thanks!

**Comment by pbrod** [comment]
Thanks for the bug-report. I will have a look into this.

All the methods in the numdifftools package have their pros and cons.
Algopy methods are generally faster and most accurate, but they can only be used on numpy functions. nd_algopy is usually easier to use than calling algopy directly, but forward method does not work on all problems.

The finite difference methods works on any functions as long as the scale of the function is reasonable.
For the complex method with n=1, you get about the same speed/accuracy as algopy. The con with the complex method is that it does not work on non-analytic functions like max, min, abs.
