### ISSUE TITLE
question about the wheel

### ISSUE THREAD

**Issue by stonebig** [pbrod/numdifftools#26]
What is the function of that enormous object of 8_201_869 byte in the pypi  wheel ? it makes the wheel  pretty big, compared to the source .zip

numdifftools-0.9.20.data/data/share/numdifftools/docs/_build/doctrees/environment.pickle	8201869

**Comment by pbrod** [comment]
I don't know, but I guess it is the content of the numdifftools/docs. I will remove it in the next release.
