### ISSUE TITLE
Change reference for dea3?

### ISSUE THREAD

**Issue by cdeil** [pbrod/numdifftools#3]
@pbrod For the `dea3` extrapolation method you're currently citing (see [here](https://github.com/pbrod/numdifftools/blob/44b3506dbe8e7b5f7059356d3acc77b602c75c9b/numdifftools/core.py#L270):

> C. Brezinski (1977)
>            "Acceleration de la convergence en analyse numerique",
>            "Lecture Notes in Math.", vol. 584,
>            Springer-Verlag, New York, 1977.

Is there another reference for this method that's freely available on the internet and preferably in English?

cc @maniteja123

**Comment by cdeil** [comment]
With Google I found a few webpages and papers discussing "Wynn's epsilon method", e.g.
* http://mathworld.wolfram.com/WynnsEpsilonMethod.html
* http://arxiv.org/pdf/math/0306302v1.pdf

Not sure which is best (i.e. the most clear description of the method implemented in `dea3` and long-term available URL)...

**Comment by pbrod** [comment]
This reference explains the Wynns epsilon algorithm in detail:

   - http://arxiv.org/pdf/math/0306302v1.pdf


It may happen that the difference between values in the epsilon table
vanishes. If pathologies of that kind occur, the so-called singular rules
of the epsilon algorithm can be used which were also derived by Wynn [39].
A good discussion of these singular rules and of related problems can also
be found in section 4.1.2 of Brezinski’s second book. (Brezinski,
Algorithmes d’acc´el´eration de la convergence – Etude num´erique ´
(Editions Technip, Paris, 1978).)

**Comment by pbrod** [comment]
Closing as I have updated Dea class to be a direct translation of dqelg function found in QUADPACK at netlib.org.
Updated the reference to QUADPACK instead as well the references mentioned above.
The dea3 function is a vectorized version of Dea class when limexp==3.
