### ISSUE TITLE
Licence clarification.

### ISSUE THREAD

**Issue by edward-dauvergne** [pbrod/numdifftools#34]
I was wondering if it would be possible to clarify the licensing text:

> * Neither the name of the {organization} nor the names of its
  contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

Here the "{organization}" part from the stock licence template is ambiguous, who does it refer to?  This is normally replaced for legal clarity.  One way that I have seen, if there is no formal organisation, is to use:

> * Neither the names of the copyright holders nor the names of any
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

Cheers,
Edward

**Comment by pbrod** [comment]
Fixed in commit [16bd526](https://github.com/pbrod/numdifftools/commit/16bd5268e32952db9b073d2a5a0a19e95a9db01c)

**Comment by pbrod** [comment]
Thank you @edward-dauvergne.
