### ISSUE TITLE
Error on evaluating gradient

### ISSUE THREAD

**Issue by nkeito** [pbrod/numdifftools#36]
Hi!
I'm facing this problem, I have a function like this:

def function( v, r, z , observation):
    return numpy.linalg.norm( observation - model(v,r,z) )   

and model is a function which takes the (vector parameters) v, r, z and returns a vector of the same size as observation, thus far, everything is ok, but when I try to compute the gradient of function, I'm facing  the next error

Traceback (most recent call last):
  File "Main.py", line 62, in <module>
    z = my_grad(  v, r, z, observation )
  File "/Users/Angel/Documents/Projects/Ursula/26Feb/Optimization/Solvers.py", line 33, in grad
    return dfun( v )
  File "/Users/Angel/anaconda/lib/python2.7/site-packages/numdifftools/nd_algopy.py", line 147, in __call__
    df = fun(x0, *args, **kwds)
  File "/Users/Angel/anaconda/lib/python2.7/site-packages/numdifftools/nd_algopy.py", line 346, in _forward
    return np.atleast_2d(super(Jacobian, self)._forward(x, *args, **kwds))
  File "/Users/Angel/anaconda/lib/python2.7/site-packages/numdifftools/nd_algopy.py", line 266, in _forward
    y = self.fun(tmp, *args, **kwds)
  File "/Users/Angel/Documents/Projects/Solvers.py", line 29, in <lambda>
    fun = lambda x: function( v, r, z , observation)
ValueError: setting an array element with a sequence.

My function to compute the gradient is as follows:

def my_grad( v, r, z , observation):
   fun = lambda x: function( v, r, z , observation)
  dfun = nda.Gradient(fun)
  return dfun( v )

I believe that I'm not making any mistake, but if you have any suggestion, please let me know

**Comment by pbrod** [comment]
Can you supply a complete example I can run?

**Comment by pbrod** [comment]
The supplied zip-file is too much. I would like a minimum example. Something like this:'

    >>> import numdifftools as nda
    >>> import numpy as np
    >>> def model(v, r, z):
    ...     return r**2+v**2 +z**2

    >>> def function( v, r, z , observation):
    ...     return numpy.linalg.norm( observation - model(v,r,z) )

    >>> def my_grad( v, r, z , observation):
    ...     v, r, z, obs = np.atleast_1d(v,r,z, observation)
    ...     fun = lambda x: function( x[0], x[1], x[2] , obs)
    ...     dfun = nda.Gradient(fun)
    ...     return dfun( v )

        >>> def my_grad( v, r, z , observation):
    ...     v, r, z, obs = np.atleast_1d(v,r,z, observation)
    ...     fun = lambda x: function( x[0], x[1], x[2] , obs)
    ...     dfun = nda.Gradient(fun)
    ...     return dfun( v )

    >>> my_grad([0,2,3],[1,2,3], [1,2,3], [3,2,1])
    array([  0.        ,   6.90919578,  10.36379367])

**Comment by nkeito** [comment]
Since model is non standard function, nor a simple  one, that is why I decided to attach the whole proyect.
But the key lines which involve the actual values of v (vel) are:

for k in range(1,n-1):
    deno[k-1] = dens[k-1]*vel[k-1] + dens[k]*vel[k]
    rd[k]   = (dens[k-1]*vel[k-1] - dens[k]*vel[k] ) / deno[k-1]
    td[k]   = 2.0 * np.sqrt(dens[k]*vel[k]*dens[k-1]*vel[k-1]) / deno[k-1] 

  for k  in range(n-2,-1,-1):
    ed =  np.exp(1j * om * ( thick[k]/vel[k] ) )

    #Do some computations and store it in variable output
    wz = np.fft.fft(output).real 
    return wz

The actual implementation is in the folder Model/models.py

**Comment by pbrod** [comment]
From your code it looks like you are using the easy to use interface to algopy.  Then you must take extra care inside your functions, because you can not use numpy.ndarray with algopy.UTPM or algopy.Function as elements!

See http://pythonhosted.org/algopy/#issues-and-common-pitfalls on how to fix this in your code.

The fastest quickfix is to replace

     import numdifftools.nd_algopy as nda 
with

    import numdifftools as nda 

In addition you replace 

    fun = lambda x: function( v, r, z , obs)
with

    fun = lambda x: function( x[0], x[1], x[2] , obs)

**Comment by nkeito** [comment]
I think that I see your point, but in my implementation, v, r and z are vectors, but, I only want to compute the gradient with respect to the x variable.

**Comment by pbrod** [comment]
I would strongly suggest that you try numdifftools first like this:

    >>> import numdifftools as nda
    >>> def my_grad2( v, r, z , observation):
    ...     v, r, z, obs = np.atleast_1d(v,r,z, observation)
    ...     fun = lambda x: function( x, r, z , obs)
    ...     dfun = nda.Gradient(fun)
    ...     return dfun( v )

    >>> my_grad2([0,2,3],[1,2,3], [1,2,3], [3,2,1])
    array([ 0.        ,  1.43499201,  5.59646883])

The result shown here is very close to the theoretical exact answer which is:
     (0, 1.4349920066683506, 5.5964688260065669)

**Comment by pbrod** [comment]
Closing since it is old.
