### ISSUE TITLE
Unable to install on Python 2.7

### ISSUE THREAD

**Issue by rparini** [pbrod/numdifftools#37]
I can't get numdifftools to install with python 2.7.  I resolved the error 
```
RuntimeError: Due to a bug in setuptools, PyScaffold currently needs at least Python 3.4! Install PyScaffold 2.5 for Python 2.7 support.
```
by changing in setup.py 
```Python
setup(setup_requires=['pyscaffold>=3.0a0,<3.1a0'] + sphinx,
```
to 
```python
setup(setup_requires=['pyscaffold==2.5.10'] + sphinx,
```
(2.5.10 is needed to work with setuptools version >= 39 due to blue-yonder/pyscaffold#148).  But I then get the error 
```
error: 'egg_base' must be a directory name (got `src`)
```
which is the setuptools bug that the PyScaffold docs say you need to use PyScaffold 2.5 to avoid.  It might be that the project needs to be set up with PyScaffold 2.5 in the first place as well as installed with it.  When I go back to the commit https://github.com/pbrod/numdifftools/commit/406a79877e0dd45aefe210b08e73cdd58ff4cb15 (just before numdifftools was updated with PyScaffold 3) then I can get it to install on python 2.7 if I downgrade setuptools to < 39.

**Comment by pbrod** [comment]
Thanks for reporting. I will look at it soon.

**Comment by pbrod** [comment]
Ok. I have reset the setup.py to

    setup(setup_requires=['pyscaffold==2.5.11'] + sphinx,

Then it works for python version 3.4, 3.5 and 3.6, but not 2.7. It seems to me that this is actually a bug in setuptools: https://github.com/pypa/setuptools/issues/1136.

**Comment by pbrod** [comment]
Setting setup.py to 

    setup(setup_requires=['pyscaffold==2.5.11'] + sphinx,
           package_dir = {'': 'src'},
           packages=find_packages(where=r'./src'),...

seems to be a workable solution in commit 7db83c8582a3c1c222c308202e5b2d545bfdb1ba.

Therfore I am closing the issue.

**Comment by rparini** [comment]
Yes, this works for me now, thank you.
