### ISSUE TITLE
complex hessian matrix

### ISSUE THREAD

**Issue by rperrier1** [pbrod/numdifftools#38]
Hi,
I went through the following issue recently while trying to compute the Hessian matrix of a cost function which outputs complex numbers. Note that there is no similar problem while evaluating the gradient.
numdifftools casts the imaginary part and return a real matrix. I made a dirty fix in forcing the `hess` variable in line 943 of core.py to be complex and it does work, so I guess it should be easy to correct.

Here is a toy example to reproduce the problem:
```
import numpy as np
import numdifftools as nd

def foo(x):
    return np.inner(x, x)-1j

x = np.random.randn(3)
hessn = nd.Hessian(foo)

hessn(x)
```
which outputs in my case:
`C:\MyPrograms\Anaconda3\lib\site-packages\numdifftools\core.py:947: ComplexWarning: Casting complex values to real discards the imaginary part
  ) / (4. * hess[i, i])`

Thanks a lot for this great tool that you provide!

**Comment by pbrod** [comment]
Thanks for reporting. I will have a look at it soon.

**Comment by pbrod** [comment]
Ok. It is fixed in commit https://github.com/pbrod/numdifftools/commit/3176049f732cfa4b06d0a4f18fffa3e3c5374d46
