### ISSUE TITLE
Put docs on readthedocs?

### ISSUE THREAD

**Issue by cdeil** [pbrod/numdifftools#4]
As a follow-up to #2 I'd like to suggest to put the numdifftools on https://readthedocs.org/ .
This would be very useful to have for users and the scipy.diff discussions.

@pbrod - It's very easy to set up and usually work directly. If you your into any issues (assuming you want this for numdifftools), let me know and I'll try to help, I've done this for a few Python packages and know where to look e.g. in the Sphinx build log if there's some error.

cc @maniteja

**Comment by pbrod** [comment]
I agree. This was the plan. I just wanted to update the docs with the
Wynn's extrapolation method, but before I managed to published it, I got
the error you saw. I will look into it in the weekend. Now I am on my way
to Italy.

;-) Per A.

**Comment by pbrod** [comment]
Fixed long ago. Closing the issue.
