### ISSUE TITLE
 ModuleNotFoundError: No module named 'info'

### ISSUE THREAD

**Issue by alla15747** [pbrod/numdifftools#41]
How to fix this issue?

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-a3397d88b620> in <module>()
      1 import numpy as np
----> 2 import numdifftools as nd
      3 fd = nd.Derivative(np.exp)              # 1'st derivative
      4 fdd = nd.Derivative(np.exp,derOrder=2)  # 2'nd derivative
      5 fd(1)

~\Anaconda3\lib\site-packages\numdifftools\__init__.py in <module>()
----> 1 from info import __doc__
      2 from core import *
      3 
      4 from numpy.testing import Tester
      5 test = Tester().test

ModuleNotFoundError: No module named 'info'

**Comment by pbrod** [comment]
Not an issue anymore. Closing.
