### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by twiecki** [pbrod/numdifftools#42]
Seems like the last release is some time ago and there are some deprecations, like:
```
/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/numdifftools/core.py:330: DeprecationWarning: `factorial` is deprecated!
Importing `factorial` from scipy.misc is deprecated in scipy 1.0.0. Use `scipy.special.factorial` instead.
  misc.factorial(np.arange(offset, step * nterms + offset, step))
```

That seem fixed on master but not in that latest release. This would make PyMC3's life easier.

**Comment by cdeil** [comment]
Yes, @pbrod could you please make a new release?

https://pypi.org/project/Numdifftools/#history

**Comment by mihaic** [comment]
Now that SciPy version 1.3.0 is out, the deprecation warnings have turned into errors. Any chance for a new release?

**Comment by pbrod** [comment]
New release of version 0.9.38 is finally uploaded to pypi. Co closing this.
