### ISSUE TITLE
Return gradient _and_ value

### ISSUE THREAD

**Issue by mayou36** [pbrod/numdifftools#50]
In minimization, often the gradient and the function value is needed at the same time. It would be useful to allow to not only return e.g. the gradient but also the value of the function at which the gradient was computed.

(Gradient <=> same for Hesse etc)

What do you think about the feasibility?

**Comment by pbrod** [comment]
I have added this value to the named info tuple as you can see in these examples:

     >>> import numdifftools as nd
     >>> rosen = lambda x : (1-x[0])**2 + 105.*(x[1]-x[0]**2)**2^M
     >>>  grad_rosen = nd.Gradient(rosen, full_output=True)
     >>> dr, info = grad_rosen((0,1))
     >>> dr, info.f_value
     (array([ -2., 210.]), 106.0)
     >>> rosen((0,1))
     106
     >>> Hfun = nd.Hessian(rosen, full_output=True)
     >>> ddr, info2 = Hfun((1,1))
     >>> ddr, info2.f_value
     (array([[ 842., -420.],
        [-420.,  210.]]), 0.0)
