### ISSUE TITLE
Gradient fails when full_output=True [AttributeError: 'tuple' object has no attribute 'squeeze']

### ISSUE THREAD

**Issue by Alexander-Serov** [pbrod/numdifftools#52]
Here is an MWE:
```
import numdifftools as nd

res = nd.Gradient(lambda x, y: x + y, full_output=False)(1, 3)
res = nd.Gradient(lambda x, y: x + y, full_output=True)(1, 3)
```
The last line fails with
```
File "C:\Python37\lib\site-packages\numdifftools\core.py", line 748, in __call__
    *args, **kwds).squeeze()
AttributeError: 'tuple' object has no attribute 'squeeze'
```
It seems like `Gradient` tries to apply `squeeze` to the output tuple containing both the result and the `full_output` object.

**Comment by pbrod** [comment]
Thanks for reporting. This is clearly a bug.

**Comment by pbrod** [comment]
closed in commit [5523e3](https://github.com/pbrod/numdifftools/commit/5523e3cf74a0d5b31ec35920684747b35c18442b)
