### ISSUE TITLE
Unit Tests fail

### ISSUE THREAD

**Issue by arthus701** [pbrod/numdifftools#54]
Hi!
I'm trying to bring numdifftools over to [nixpkgs](https://search.nixos.org/packages). When building, the last 5 unit tests fail (`test_wprofiletools.py`). Is this a known problem? Please let me know if I can assist in fixing the issue. I attached the test-log for further insight.

[ndtools_log.txt](https://github.com/pbrod/numdifftools/files/5473842/ndtools_log.txt)

**Comment by pbrod** [comment]
The errors occur because the lineprofiler is missing.
Installing the lineprofiler will fix it.

**Comment by arthus701** [comment]
Works like a charm, thank you!
