### ISSUE TITLE
Hessian fails with strange error when function returns inf

### ISSUE THREAD

**Issue by pkienzle** [pbrod/numdifftools#6]
Example:

import numdifftools as nd
import numpy as np
def finf(x): return np.inf
nd.Hessian(finf)([0.1])

numdifftools/core.pyc in _romb_extrap(self, der_init, h1)
-->             errest = np.ones(der_init.shape) * hout
ValueError: operands could not be broadcast together with shapes (24,) (0,) 

Since all values are infinite, the _remove_non_finite leaves hout empty, hence the error.

**Comment by pbrod** [comment]
Thanks I have fixed it in numdifftools.nd_cstep module. This will soon replace numdifftools.core.

**Comment by pbrod** [comment]
This is now fixed in version 0.9.2.
