### ISSUE TITLE
Add suggested reference for numdifftools?

### ISSUE THREAD

**Issue by kyleniemeyer** [pbrod/numdifftools#8]
Do you have a suggested way to cite numdifftools in a research article? My current approach would be to  include a link to the GitHub repo, something like
```
@misc{Brodtkorb:2015,
	Author = {Per A Brodtkorb},
	Title = {numdifftools 0.9.2},
	Howpublished = {\url{https://github.com/pbrod/numdifftools}},
	Month = aug,
	Year = {2015}}
```
but if there is a "better"/official reference, I'd prefer to use that.

**Comment by pbrod** [comment]
numdifftools is heavily based on the matlab toolboox DerivestSuite by John D’Errico (2006), http://www.mathworks.com/matlabcentral/fileexchange/13490-adaptive-robust-numerical-differentiation.

I think the most correct would be to also include him in the reference. Maybe something like this

@misc{BrodtkorbAndDErrico:2015,
    Author = {Per A Brodtkorb and John D'Errico},
    Title = {numdifftools 0.9.11},
    Howpublished = {\url{https://github.com/pbrod/numdifftools}},
    Month = aug,
    Year = {2015}}

**Comment by kyleniemeyer** [comment]
OK, thanks!
